#!/bin/bash
# gst-launch-1.0 'nvarguscamerasrc ! video/x-raw(memory:NVMM), width=(int)3264, height=(int)2464, format=(string)NV12, framerate=(fraction)60/1 !  ! videoconvert ! video/x-raw, width=(int)1280,height=(int)720,format=(string)BGRx  ! nvoverlaysink'
gst-launch-1.0 nvarguscamerasrc tnr-mode=2 tnr-strength=1 saturation=2 ! 'video/x-raw(memory:NVMM), width=640, height=480, format=NV12,framerate=60/1' ! nvvidconv ! video/x-raw, width=640, height=480 ! appsink #   ximagesink
